package view;

import java.awt.BorderLayout;
import java.awt.Component;
import java.util.List;
import java.util.Vector;

import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

import model.Project;
import controller.ProjectController;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Soumya
 */
public class SearchProjectView extends javax.swing.JInternalFrame {
	private ProjectController projectController = new ProjectController();
    /**
     * Creates new form SearchProjectView
     */
    public SearchProjectView() {
        initComponents();
        JTable jt = getProjectsListTable(projectController.getAllProjectList());
    	JScrollPane scrollpane = new JScrollPane(jt);
    	projectListTable.setLayout(new BorderLayout());
    	projectListTable.add(scrollpane, BorderLayout.CENTER);
    	TableCellRenderer buttonRenderer = new JTableButtonRenderer();
        jt.getColumn("View/Edit").setCellRenderer(buttonRenderer);
        jt.getColumn("Delete").setCellRenderer(buttonRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        projectListPanel = new javax.swing.JPanel();
        projectListTable = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblSearchProject = new javax.swing.JLabel();
        txtSearchCriteria = new javax.swing.JTextField();
        comboSearchBy = new javax.swing.JComboBox();
        btnSearchProjects = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser1.setVisible(false);

        projectListPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Project List"));

        javax.swing.GroupLayout projectListTableLayout = new javax.swing.GroupLayout(projectListTable);
        projectListTable.setLayout(projectListTableLayout);
        projectListTableLayout.setHorizontalGroup(
            projectListTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        projectListTableLayout.setVerticalGroup(
            projectListTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout projectListPanelLayout = new javax.swing.GroupLayout(projectListPanel);
        projectListPanel.setLayout(projectListPanelLayout);
        projectListPanelLayout.setHorizontalGroup(
            projectListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectListTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        projectListPanelLayout.setVerticalGroup(
            projectListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectListTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Projects"));

        lblSearchProject.setText("Search");

        txtSearchCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchCriteriaActionPerformed(evt);
            }
        });

        comboSearchBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Project Name", "Status", "Start Date", "End Date", "Participant Name", "Participant Role", "Category" }));
        comboSearchBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSearchByActionPerformed(evt);
            }
        });

        btnSearchProjects.setIcon(new javax.swing.ImageIcon("C:\\Users\\Soumya\\workspace\\FrugalLabProject\\FrugalLabProject\\src\\images\\search.png")); // NOI18N
        btnSearchProjects.setText("Search");
        btnSearchProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProjectsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblSearchProject, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearchProjects)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSearchProject, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSearchCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSearchProjects)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(projectListPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(projectListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void txtSearchCriteriaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void comboSearchByActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if(comboSearchBy.getSelectedIndex()==2 ||comboSearchBy.getSelectedIndex()==3){
        	jDateChooser1.setVisible(true);
        	txtSearchCriteria.setVisible(false);
        }else{
        	jDateChooser1.setVisible(false);
        	txtSearchCriteria.setVisible(true);
        }
    }                                             

    private void btnSearchProjectsActionPerformed(java.awt.event.ActionEvent evt) { 
    	
    } 
    
    public JTable getProjectsListTable(List<Project> projectList){
    	Vector<String> columnNames = new Vector<String>();
    	columnNames.add("Project Name");
    	columnNames.add("Status");
    	columnNames.add("Start Date");
    	columnNames.add("End Date");
    	columnNames.add("Outcome");
    	columnNames.add("Location");
    	columnNames.add("View/Edit");
    	columnNames.add("Delete");
    	Vector<Vector> projectsData = new Vector<Vector>();
    	for(Project project:projectList){
    		Vector<Object> projData = new Vector<Object>();
    		projData.add(project.getProjectName());
    		projData.add(project.getStatus());
    		projData.add(project.getStartDate());
    		projData.add(project.getEndDate());
    		projData.add(project.getOutcome());
    		projData.add(project.getCountry());
			final int id = project.getProjectID();
    		if(true){
    			JButton viewBtn = new JButton("View/Edit");
    			viewBtn.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	            	viewProject(id);
    	            }
    	        });
    			projData.add(viewBtn);
    			JButton deleteBtn = new JButton("Delete");
    			deleteBtn.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	            	deleteProject(id);
    	            }
    	        });
    			projData.add(deleteBtn);
    		}
    		projectsData.add(projData);
    	}
    	JTable projectTable = new JTable(projectsData, columnNames);
    	return projectTable;
    }
    public void viewProject(Integer id){
    	
    }
    public void deleteProject(Integer id){
    	
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnSearchProjects;
    private javax.swing.JComboBox comboSearchBy;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSearchProject;
    private javax.swing.JPanel projectListPanel;
    private javax.swing.JPanel projectListTable;
    private javax.swing.JTextField txtSearchCriteria;
    // End of variables declaration                   
}
class JTableButtonRenderer implements TableCellRenderer {        
    @Override public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        JButton button = (JButton)value;
        return button;  
    }
}
