package view;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.Properties;

import javax.imageio.ImageIO;
import javax.persistence.TypedQuery;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JInternalFrame;

import model.ProjectSummary;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

import controller.ProjectProperties;
import controller.SearchProjectController;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Soumya
 */
public class StartUpView extends javax.swing.JFrame {
    private LoginView alv;
    private ProjectView pv;
    private ParticipantView participantView;
    private CategoryView cv = new CategoryView();

    SearchProjectView sv;
    private ProjectProperties properties;
    private SearchProjectController searchProjectController;

    /**
     * Creates new form StartUpView
     */
    public StartUpView() {
        properties = new ProjectProperties();
        initComponents();
        alv = new LoginView(optionPane,btnLoginMenu,btnlogout,setProjectsDirectory,btnAddProject);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        int scrnHigh = d.height;
        int scrnWide = d.width;
        setSize(scrnWide, scrnHigh);
        setLocation(0, 0);
        desktop.setSize(getSize(d));

        try {
			setIconImage(ImageIO.read(new File("images/3_dots.png")));

        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        ProjectProperties.isAdminMode = false;
        changeMode(ProjectProperties.isAdminMode);
        searchProjectController = new SearchProjectController(desktop);
        sv = new SearchProjectView(desktop);
        pv = new ProjectView(desktop);
        desktop.add(sv);
        sv.show();

    }
    public void removeAllInternalFrame(){
        for(Component c:desktop.getComponents()){
            System.out.println(c.getName());
            c.hide();
            desktop.remove(c);
        }
    }

    public void changeMode(boolean mode){
        optionPane.setEnabledAt(1, mode);
        optionPane.setEnabledAt(2, mode);
        btnLoginMenu.setVisible(!mode);
        btnlogout.setVisible(mode);
        setProjectsDirectory.setVisible(mode);
        btnAddProject.setVisible(mode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        desktop = new javax.swing.JDesktopPane();
        optionPane = new javax.swing.JTabbedPane();
        projectPane = new javax.swing.JPanel();
        btnSearchProject = new javax.swing.JButton();
        btnAddProject = new javax.swing.JButton();
        btnStatistics = new javax.swing.JButton();
        participantPane = new javax.swing.JPanel();
        btnSearchParticipant = new javax.swing.JButton();
        btnAddParticipant = new javax.swing.JButton();
        categoryPane = new javax.swing.JPanel();
        btnSearchCategory = new javax.swing.JButton();
        btnAddCategory = new javax.swing.JButton();
        adminPane = new javax.swing.JPanel();
        btnLoginMenu = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        setProjectsDirectory = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setBackground(new java.awt.Color(255, 255, 255));
        desktop.setMinimumSize(new java.awt.Dimension(100, 100));

        optionPane.setBackground(new java.awt.Color(204, 204, 204));

        btnSearchProject.setText("Search");
        btnSearchProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProjectActionPerformed(evt);
            }
        });

        btnAddProject.setText("Add New");
        btnAddProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProjectActionPerformed(evt);
            }
        });

        btnStatistics.setText("Project Statistics");
        btnStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout projectPaneLayout = new javax.swing.GroupLayout(projectPane);
        projectPane.setLayout(projectPaneLayout);
        projectPaneLayout.setHorizontalGroup(
                projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(projectPaneLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnSearchProject)
                                .addGap(69, 69, 69)
                                .addComponent(btnAddProject)
                                .addComponent(btnStatistics)
                                .addContainerGap(387, Short.MAX_VALUE))
        );
        projectPaneLayout.setVerticalGroup(
                projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(projectPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSearchProject)
                                        .addComponent(btnAddProject)
                                        .addComponent(btnStatistics))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionPane.addTab("Project", projectPane);

        btnSearchParticipant.setText("Search");
        btnSearchParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchParticipantActionPerformed(evt);
            }
        });

        btnAddParticipant.setText("Add New");
        btnAddParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddParticipantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout participantPaneLayout = new javax.swing.GroupLayout(participantPane);
        participantPane.setLayout(participantPaneLayout);
        participantPaneLayout.setHorizontalGroup(
                participantPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(participantPaneLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnSearchParticipant)
                                .addGap(49, 49, 49)
                                .addComponent(btnAddParticipant)
                                .addContainerGap(408, Short.MAX_VALUE))
        );
        participantPaneLayout.setVerticalGroup(
                participantPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(participantPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(participantPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSearchParticipant)
                                        .addComponent(btnAddParticipant))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionPane.addTab("Participant", participantPane);

        btnSearchCategory.setText("Search");
        btnSearchCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCategoryActionPerformed(evt);
            }
        });

        btnAddCategory.setText("Add New");
        btnAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout categoryPaneLayout = new javax.swing.GroupLayout(categoryPane);
        categoryPane.setLayout(categoryPaneLayout);
        categoryPaneLayout.setHorizontalGroup(
                categoryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(categoryPaneLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnSearchCategory)
                                .addGap(54, 54, 54)
                                .addComponent(btnAddCategory)
                                .addContainerGap(391, Short.MAX_VALUE))
        );
        categoryPaneLayout.setVerticalGroup(
                categoryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(categoryPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(categoryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSearchCategory)
                                        .addComponent(btnAddCategory))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionPane.addTab("Category", categoryPane);

        adminPane.setMaximumSize(new java.awt.Dimension(100, 100));

        btnLoginMenu.setText("Login");
        btnLoginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginMenuActionPerformed(evt);
            }
        });

        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        setProjectsDirectory.setText("Set Project Directory");
        setProjectsDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setProjectsDirectoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminPaneLayout = new javax.swing.GroupLayout(adminPane);
        adminPane.setLayout(adminPaneLayout);
        adminPaneLayout.setHorizontalGroup(
                adminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(adminPaneLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnLoginMenu)
                                .addGap(99, 99, 99)
                                .addComponent(btnlogout)
                                .addComponent(setProjectsDirectory)
                                .addContainerGap(360, Short.MAX_VALUE))
        );
        adminPaneLayout.setVerticalGroup(
                adminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(adminPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(adminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnlogout)
                                        .addComponent(btnLoginMenu)
                                        .addComponent(setProjectsDirectory))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionPane.addTab("Admin Mode", adminPane);

        lblLogo.setIcon(new javax.swing.ImageIcon("images/frigal_logo.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(optionPane, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLogo))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblLogo)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(optionPane, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btnLoginMenuActionPerformed(java.awt.event.ActionEvent evt) {
        removeAllInternalFrame();
        desktop.add(alv);
        alv.show();
    }

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {
        alv.hide();
        ProjectProperties.isAdminMode = false;
        changeMode(ProjectProperties.isAdminMode);
        removeAllInternalFrame();
        sv = new SearchProjectView(desktop);
        desktop.add(sv);
        sv.show();
    }

    private void btnSearchCategoryActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	removeAllInternalFrame();
        desktop.add(cv);
        cv.show();
    }

    private void btnSearchParticipantActionPerformed(java.awt.event.ActionEvent evt) {
        removeAllInternalFrame();
        SearchParticipantView searchParticipantView = new SearchParticipantView();
        desktop.add(searchParticipantView);
        searchParticipantView.setVisible(true);
    }

    private void btnAddParticipantActionPerformed(java.awt.event.ActionEvent evt) {
        removeAllInternalFrame();
        participantView = new ParticipantView();
        desktop.add(participantView);
        participantView.setVisible(true);
    }

    private void btnSearchProjectActionPerformed(java.awt.event.ActionEvent evt) {
        removeAllInternalFrame();
        SearchProjectView sv = new SearchProjectView(desktop);
        desktop.add(sv);
        sv.show();

    }

    private void btnStatisticsActionPerformed(java.awt.event.ActionEvent evt) {
        ChartView cv = new ChartView(desktop);
        desktop.add(cv);
        cv.show();
        cv.validate();
    }

    private void btnAddProjectActionPerformed(java.awt.event.ActionEvent evt) {
        removeAllInternalFrame();
        ProjectView pv = new ProjectView(desktop);
        desktop.add(pv);
        pv.show();
    }

    private void setProjectsDirectoryActionPerformed(java.awt.event.ActionEvent evt) {
        int result;

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Select Destination Directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getSelectedFile() : "
                    +  chooser.getSelectedFile());
            try {
                FileOutputStream out = new FileOutputStream("project.properties");
                FileInputStream in = new FileInputStream("project.properties");
                Properties props = new Properties();
                props.load(in);
                in.close();
                props.setProperty("destinationPath", chooser.getSelectedFile().toString());
                props.store(out, null);
                out.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        else {
            System.out.println("No Selection ");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartUpView().setVisible(true);
            }
        });
    }

    public void showIFrame(JInternalFrame frame){
        desktop.add(frame);
        frame.show();
    }



    // Variables declaration - do not modify
    protected javax.swing.JPanel adminPane;
    protected javax.swing.JButton btnAddCategory;
    protected javax.swing.JButton btnAddParticipant;
    protected javax.swing.JButton btnAddProject;
    private javax.swing.JButton btnStatistics;
    protected javax.swing.JButton btnLoginMenu;
    protected javax.swing.JButton btnSearchCategory;
    protected javax.swing.JButton btnSearchParticipant;
    protected javax.swing.JButton btnSearchProject;
    protected javax.swing.JButton btnlogout;
    protected javax.swing.JPanel categoryPane;
    protected javax.swing.JDesktopPane desktop;
    protected javax.swing.JDialog jDialog1;
    protected javax.swing.JFrame jFrame1;
    protected javax.swing.JLabel lblLogo;
    protected javax.swing.JTabbedPane optionPane;
    protected javax.swing.JPanel participantPane;
    private javax.swing.JPanel projectPane;
    private javax.swing.JButton setProjectsDirectory;
    // End of variables declaration
}

